package org.linlinjava.litemall.db.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.linlinjava.litemall.db.domain.LitemallMemberPrice;
import org.linlinjava.litemall.db.domain.LitemallMemberPriceExample;

public interface LitemallMemberPriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_price
     *
     * @mbg.generated
     */
    long countByExample(LitemallMemberPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_price
     *
     * @mbg.generated
     */
    int deleteByExample(LitemallMemberPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_price
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String level);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_price
     *
     * @mbg.generated
     */
    int insert(LitemallMemberPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_price
     *
     * @mbg.generated
     */
    int insertSelective(LitemallMemberPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_price
     *
     * @mbg.generated
     */
    LitemallMemberPrice selectOneByExample(LitemallMemberPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_price
     *
     * @mbg.generated
     */
    LitemallMemberPrice selectOneByExampleSelective(@Param("example") LitemallMemberPriceExample example, @Param("selective") LitemallMemberPrice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_price
     *
     * @mbg.generated
     */
    List<LitemallMemberPrice> selectByExampleSelective(@Param("example") LitemallMemberPriceExample example, @Param("selective") LitemallMemberPrice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_price
     *
     * @mbg.generated
     */
    List<LitemallMemberPrice> selectByExample(LitemallMemberPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_price
     *
     * @mbg.generated
     */
    LitemallMemberPrice selectByPrimaryKeySelective(@Param("level") String level, @Param("selective") LitemallMemberPrice.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_price
     *
     * @mbg.generated
     */
    LitemallMemberPrice selectByPrimaryKey(String level);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_price
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") LitemallMemberPrice record, @Param("example") LitemallMemberPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_price
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") LitemallMemberPrice record, @Param("example") LitemallMemberPriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(LitemallMemberPrice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table litemall_member_price
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(LitemallMemberPrice record);
}